INSERT INTO look_up (
    look_up_type,
    code,
    name,
    description,
    display_order,
    log_module_created,
    log_module_updated
)
VALUES
    ('material_status', 'active', 'Active', 'Material is available for use.', 1, NULL, NULL),
    ('material_status', 'inactive', 'Inactive', 'Material is retained for history but cannot be selected for new transactions.', 2, NULL, NULL),
    ('material_request_status', 'draft', 'Draft', 'Material request is being prepared.', 1, NULL, NULL),
    ('material_request_status', 'submitted', 'Submitted', 'Material request has been submitted for review.', 2, NULL, NULL),
    ('material_request_status', 'approved', 'Approved', 'Material request has been approved.', 3, NULL, NULL),
    ('material_request_status', 'rejected', 'Rejected', 'Material request has been rejected.', 4, NULL, NULL),
    ('material_request_status', 'cancelled', 'Cancelled', 'Material request has been cancelled.', 5, NULL, NULL),
    ('material_request_status', 'completed', 'Completed', 'Material request has been fulfilled.', 6, NULL, NULL),
    ('material_request_status', 'closed', 'Closed', 'Material request has been closed.', 7, NULL, NULL),
    ('material_control_status', 'draft', 'Draft', 'Material control is being prepared.', 1, NULL, NULL),
    ('material_control_status', 'submitted', 'Submitted', 'Material control has been submitted for review.', 2, NULL, NULL),
    ('material_control_status', 'approved', 'Approved', 'Material control has been approved.', 3, NULL, NULL),
    ('material_control_status', 'rejected', 'Rejected', 'Material control has been rejected.', 4, NULL, NULL),
    ('material_control_status', 'cancelled', 'Cancelled', 'Material control has been cancelled.', 5, NULL, NULL),
    ('material_control_status', 'closed', 'Closed', 'Material control has been closed.', 6, NULL, NULL),
    ('material_brand_status', 'active', 'Active', 'Brand-specific material is available for purchasing and inventory transactions.', 1, NULL, NULL),
    ('material_brand_status', 'inactive', 'Inactive', 'Brand-specific material is retained for history but cannot be selected for new transactions.', 2, NULL, NULL),
    ('stock_movement_type', 'transfer', 'Transfer', 'Move material from one party to another.', 1, NULL, NULL),
    ('stock_movement_type', 'issue', 'Issue', 'Issue material from stock to a project or internal use.', 2, NULL, NULL),
    ('stock_movement_type', 'receipt', 'Receipt', 'Receive material into stock from a supplier or return.', 3, NULL, NULL),
    ('stock_movement_type', 'adjustment', 'Adjustment', 'Inventory adjustment for corrections.', 4, NULL, NULL),
    ('stock_movement_type', 'return', 'Return', 'Return material back to source.', 5, NULL, NULL),
    ('stock_movement_status', 'pending', 'Pending', 'Movement is created but not yet completed.', 1, NULL, NULL),
    ('stock_movement_status', 'completed', 'Completed', 'Movement has been completed.', 2, NULL, NULL),
    ('stock_movement_status', 'cancelled', 'Cancelled', 'Movement was cancelled.', 3, NULL, NULL),
    ('stock_movement_status', 'failed', 'Failed', 'Movement failed and may require correction.', 4, NULL, NULL),
    ('material_option_type', 'substitute', 'Substitute', 'Material substitute option.', 1, NULL, NULL),
    ('material_option_type', 'assembly', 'Assembly', 'Material assembly option.', 2, NULL, NULL),
    ('purchase_order_adjustment_kind', 'discount', 'Discount', 'Order-level or item-level discount.', 1, NULL, NULL),
    ('purchase_order_adjustment_kind', 'charge', 'Charge', 'Order-level or item-level additional charge.', 2, NULL, NULL),
    ('address_type', 'home', 'HOME', 'Residential home address.', 1, NULL, NULL),
    ('address_type', 'office', 'OFFICE', 'Office or business address.', 2, NULL, NULL),
    ('address_type', 'warehouse', 'WAREHOUSE', 'Warehouse or storage location address.', 3, NULL, NULL),
    ('address_type', 'billing', 'BILLING', 'Billing and invoicing address.', 4, NULL, NULL),
    ('address_type', 'shipping', 'SHIPPING', 'Shipping or delivery destination address.', 5, NULL, NULL),
    ('address_type', 'project_site', 'PROJECT_SITE', 'Project site or job location address.', 6, NULL, NULL),
    ('NAME_PREFIX', 'mr', 'MR', 'Mister prefix.', 1, NULL, NULL),
    ('NAME_PREFIX', 'mrs', 'MRS', 'Missus prefix.', 2, NULL, NULL),
    ('NAME_PREFIX', 'ms', 'MS', 'Ms prefix.', 3, NULL, NULL),
    ('NAME_PREFIX', 'dr', 'DR', 'Doctor prefix.', 4, NULL, NULL),
    ('NAME_PREFIX', 'engr', 'ENGR', 'Engineer prefix.', 5, NULL, NULL),
    ('NAME_PREFIX', 'atty', 'ATTY', 'Attorney prefix.', 6, NULL, NULL),
    ('NAME_PREFIX', 'prof', 'PROF', 'Professor prefix.', 7, NULL, NULL),
    ('NAME_SUFFIX', 'jr', 'JR', 'Junior suffix.', 1, NULL, NULL),
    ('NAME_SUFFIX', 'sr', 'SR', 'Senior suffix.', 2, NULL, NULL),
    ('NAME_SUFFIX', 'ii', 'II', 'Second generation suffix.', 3, NULL, NULL),
    ('NAME_SUFFIX', 'iii', 'III', 'Third generation suffix.', 4, NULL, NULL),
    ('NAME_SUFFIX', 'iv', 'IV', 'Fourth generation suffix.', 5, NULL, NULL),
    ('NAME_SUFFIX', 'v', 'V', 'Fifth generation suffix.', 6, NULL, NULL),
    ('ENTITY_TYPE', 'person', 'PERSON', 'Individual person contact.', 1, NULL, NULL),
    ('ENTITY_TYPE', 'company', 'COMPANY', 'Company or organization contact.', 2, NULL, NULL),
    ('ENTITY_TYPE', 'department', 'DEPARTMENT', 'Department-level contact under a company.', 3, NULL, NULL),
    ('ENTITY_TYPE', 'project', 'PROJECT', 'Project contact node.', 4, NULL, NULL),
    ('PHONE_TYPE', 'mobile', 'MOBILE', 'Mobile Phone', 1, NULL, NULL),
    ('PHONE_TYPE', 'home', 'HOME', 'Home Phone', 2, NULL, NULL),
    ('PHONE_TYPE', 'office', 'OFFICE', 'Office Phone', 3, NULL, NULL),
    ('PHONE_TYPE', 'fax', 'FAX', 'Fax Number', 4, NULL, NULL),
    ('PHONE_TYPE', 'whatsapp', 'WHATSAPP', 'WhatsApp Number', 5, NULL, NULL),
    ('PHONE_TYPE', 'emergency', 'EMERGENCY', 'Emergency Contact Number', 6, NULL, NULL),
    ('EMAIL_TYPE', 'personal', 'PERSONAL', 'Personal Email', 1, NULL, NULL),
    ('EMAIL_TYPE', 'work', 'WORK', 'Work Email', 2, NULL, NULL),
    ('EMAIL_TYPE', 'billing', 'BILLING', 'Billing Email', 3, NULL, NULL),
    ('EMAIL_TYPE', 'support', 'SUPPORT', 'Support Email', 4, NULL, NULL),
    ('EMAIL_TYPE', 'notification', 'NOTIFICATION', 'Notification Email', 5, NULL, NULL),
    ('party_type', 'project', 'Project', 'Project party used for project-level transactions.', 1, NULL, NULL),
    ('party_type', 'warehouse', 'Warehouse', 'Warehouse party used for stock holding and transfers.', 2, NULL, NULL),
    ('party_type', 'services', 'Services', 'Service provider party used for job order or service transactions.', 3, NULL, NULL),
    ('party_type', 'external', 'External', 'External party used for non-standard third-party transactions.', 4, NULL, NULL),
    ('party_type', 'supplier', 'Supplier', 'Supplier party used for purchasing and supplier delivery transactions.', 5, NULL, NULL),
    ('party_status', 'active', 'Active', 'Party is active and available for transactions.', 1, NULL, NULL),
    ('party_status', 'inactive', 'Inactive', 'Party is inactive and cannot be selected for new transactions.', 2, NULL, NULL),
    ('project_type', 'project', 'Project', 'Project party used for project-level transactions.', 1, NULL, NULL),
    ('project_type', 'warehouse', 'Warehouse', 'Warehouse party used for stock holding and transfers.', 2, NULL, NULL),
    ('project_type', 'services', 'Services', 'Service provider party used for job order or service transactions.', 3, NULL, NULL),
    ('project_type', 'external', 'External', 'External party used for non-standard third-party transactions.', 4, NULL, NULL),
    ('payment_terms', 'cod', 'Cash on Delivery', 'Payment due upon delivery.', 1, NULL, NULL),
    ('payment_terms', 'net15', 'Net 15', 'Payment due 15 days after invoice date.', 2, NULL, NULL),
    ('payment_terms', 'net30', 'Net 30', 'Payment due 30 days after invoice date.', 3, NULL, NULL),
    ('payment_terms', 'net60', 'Net 60', 'Payment due 60 days after invoice date.', 4, NULL, NULL)
ON CONFLICT (look_up_type, name) DO NOTHING;
