CREATE TABLE look_up (
    look_up_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    look_up_type TEXT NOT NULL,
    code TEXT,
    name TEXT NOT NULL,
    description TEXT,
    display_order BIGINT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_look_up_type_name UNIQUE (look_up_type, name)
);

CREATE INDEX idx_look_up_type ON look_up(look_up_type);
