CREATE TABLE sub_category (
    sub_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES category(category_id),
    sub_category_code TEXT NOT NULL UNIQUE,
    sub_category_name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_sub_category_category_name UNIQUE (category_id, sub_category_name)
);

CREATE INDEX idx_sub_category_category_id ON sub_category(category_id);
