CREATE TABLE material (
    material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    source_description TEXT,
    category_id BIGINT NOT NULL REFERENCES category(category_id),
    sub_category_id BIGINT REFERENCES sub_category(sub_category_id),
    stock_uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_material_category_id ON material(category_id);
CREATE INDEX idx_material_sub_category_id ON material(sub_category_id);
CREATE INDEX idx_material_stock_uom_id ON material(stock_uom_id);
CREATE INDEX idx_material_status_id ON material(status_id);
