CREATE TABLE material_brand (
    material_brand_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    brand_id BIGINT NOT NULL REFERENCES brand(brand_id),
    brand_product_code TEXT,
    brand_product_name TEXT,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_material_brand_material_brand UNIQUE (material_id, brand_id)
);

CREATE INDEX idx_material_brand_material_id ON material_brand(material_id);
CREATE INDEX idx_material_brand_brand_id ON material_brand(brand_id);
CREATE INDEX idx_material_brand_status_id ON material_brand(status_id);
