CREATE TABLE material_option (
    material_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    option_code TEXT NOT NULL UNIQUE,
    option_name TEXT NOT NULL,
    option_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_material_option_material_id
    ON material_option(material_id);
CREATE INDEX idx_material_option_option_type_id
    ON material_option(option_type_id);
