CREATE TABLE material_option_detail (
    material_option_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_option_id BIGINT NOT NULL
        REFERENCES material_option(material_option_id) ON DELETE CASCADE,
    component_material_id BIGINT NOT NULL REFERENCES material(material_id),
    required_quantity NUMERIC NOT NULL,
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT chk_material_option_detail_quantity
        CHECK (required_quantity > 0),
    CONSTRAINT uq_material_option_component
        UNIQUE (material_option_id, component_material_id)
);

CREATE INDEX idx_material_option_detail_component_material_id
    ON material_option_detail(component_material_id);
