CREATE TABLE contact (
    contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_contact_id BIGINT REFERENCES contact(contact_id),
    entity_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    prefix_id BIGINT REFERENCES look_up(look_up_id),
    first_name TEXT,
    middle_name TEXT,
    last_name TEXT,
    suffix_id BIGINT REFERENCES look_up(look_up_id),
    contact_name TEXT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_contact_parent_contact_id ON contact(parent_contact_id);
CREATE INDEX idx_contact_entity_type_id ON contact(entity_type_id);
CREATE INDEX idx_contact_last_name ON contact(last_name);
CREATE INDEX idx_contact_contact_name ON contact(contact_name);
