CREATE TABLE stock_movement (
    stock_movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES party(party_id),
    destination_id BIGINT NOT NULL REFERENCES party(party_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    quantity NUMERIC NOT NULL,
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    movement_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    movement_date TIMESTAMPTZ NOT NULL,
    reference_code TEXT,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_stock_movement_source_id ON stock_movement(source_id);
CREATE INDEX idx_stock_movement_destination_id ON stock_movement(destination_id);
CREATE INDEX idx_stock_movement_material_id ON stock_movement(material_id);
CREATE INDEX idx_stock_movement_material_brand_id ON stock_movement(material_brand_id);
CREATE INDEX idx_stock_movement_movement_type_id ON stock_movement(movement_type_id);
CREATE INDEX idx_stock_movement_status_id ON stock_movement(status_id);
CREATE INDEX idx_stock_movement_movement_date ON stock_movement(movement_date);
