CREATE TABLE party (
    party_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contact(contact_id),
    party_code TEXT NOT NULL UNIQUE,
    party_name TEXT NOT NULL,
    party_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    description TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_party_contact_id ON party(contact_id);
CREATE INDEX idx_party_party_type_id ON party(party_type_id);
CREATE INDEX idx_party_status_id ON party(status_id);
