CREATE TABLE stock_balance (
    stock_balance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL REFERENCES party(party_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    quantity_on_hand NUMERIC NOT NULL DEFAULT 0,
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_stock_balance_party_material_brand_uom UNIQUE (party_id, material_id, material_brand_id, uom_id)
);

CREATE INDEX idx_stock_balance_party_id ON stock_balance(party_id);
CREATE INDEX idx_stock_balance_material_id ON stock_balance(material_id);
CREATE INDEX idx_stock_balance_material_brand_id ON stock_balance(material_brand_id);
CREATE INDEX idx_stock_balance_uom_id ON stock_balance(uom_id);
