CREATE TABLE address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contact(contact_id),
    address_type_id BIGINT REFERENCES look_up(look_up_id),
    address_label TEXT,
    house_no TEXT,
    street TEXT,
    barangay TEXT,
    city TEXT,
    province TEXT,
    region TEXT,
    country_code CHAR(2),
    postal_code TEXT,
    attention_to TEXT,
    delivery_instruction TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ DEFAULT NOW(),
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT REFERENCES account(account_id),
    log_updated_by_account_id BIGINT REFERENCES account(account_id),
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT REFERENCES account(account_id),
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_address_contact_id ON address(contact_id);

CREATE UNIQUE INDEX uq_address_contact_active_primary
ON address(contact_id)
WHERE is_primary = TRUE
    AND is_deleted = FALSE;
