CREATE TABLE stock_layer (
    stock_layer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL REFERENCES party(party_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    quantity_received NUMERIC NOT NULL,
    quantity_available NUMERIC NOT NULL,
    receive_date TIMESTAMPTZ NOT NULL,
    source_movement_id BIGINT REFERENCES stock_movement(stock_movement_id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_stock_layer_party_material ON stock_layer(party_id, material_id, material_brand_id);
CREATE INDEX idx_stock_layer_receive_date ON stock_layer(receive_date);
CREATE INDEX idx_stock_layer_source_movement_id ON stock_layer(source_movement_id);
