CREATE TABLE phone (
    phone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contact(contact_id),
        phone_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    phone_number TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        log_date_created TIMESTAMPTZ DEFAULT NOW(),
    log_date_updated TIMESTAMPTZ,
        log_created_by_account_id BIGINT REFERENCES account(account_id),
        log_updated_by_account_id BIGINT REFERENCES account(account_id),
    log_date_deleted TIMESTAMPTZ,
        log_deleted_by_account_id BIGINT REFERENCES account(account_id),
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_phone_contact_id ON phone(contact_id);
CREATE INDEX idx_phone_type_id ON phone(phone_type_id);

CREATE UNIQUE INDEX uq_phone_contact_active_primary
ON phone(contact_id)
WHERE is_primary = TRUE
    AND is_deleted = FALSE;
