CREATE TABLE email (
    email_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contact(contact_id),
        email_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    email_address TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        log_date_created TIMESTAMPTZ DEFAULT NOW(),
    log_date_updated TIMESTAMPTZ,
        log_created_by_account_id BIGINT REFERENCES account(account_id),
        log_updated_by_account_id BIGINT REFERENCES account(account_id),
    log_date_deleted TIMESTAMPTZ,
        log_deleted_by_account_id BIGINT REFERENCES account(account_id),
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_email_contact_id ON email(contact_id);
CREATE INDEX idx_email_type_id ON email(email_type_id);

CREATE UNIQUE INDEX uq_email_contact_active_primary
ON email(contact_id)
WHERE is_primary = TRUE
    AND is_deleted = FALSE;
