CREATE TABLE email (
    email_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contact(contact_id),
    email_label TEXT,
    email_address TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_email_contact_id ON email(contact_id);
