-- Migration: 017_user.sql
-- Creates the central `user` table linked to `party` for contact/profile data
CREATE TABLE "user" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    contact_id BIGINT REFERENCES contact(contact_id),
    password_hash TEXT,
    full_name TEXT,
    profile JSONB,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ DEFAULT now(),
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

-- Uniqueness on username/email scoped to non-deleted users can be enforced in app
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_user_name ON "user"(user_name);
-- `email` removed: use `contact`/`email` table for user contact addresses
CREATE INDEX IF NOT EXISTS idx_user_contact_id ON "user"(contact_id);
-- user contact details live under `contact` -> `address`/`phone`/`email`
