-- Migration: 019_permission.sql
CREATE TABLE permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name TEXT NOT NULL,
    permission_code TEXT NOT NULL,
    permission_name TEXT NOT NULL,
    description TEXT,
    meta JSONB,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ DEFAULT now(),
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_permission_module_code UNIQUE (module_name, permission_code)
);

CREATE INDEX IF NOT EXISTS idx_permission_module ON permission(module_name);
