-- Migration: 021_account_role.sql
CREATE TABLE account_role (
    account_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES account(account_id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES role(role_id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ DEFAULT now(),
    log_created_by_account_id BIGINT,
    log_module_created TEXT
);

ALTER TABLE account_role ADD CONSTRAINT uq_account_role UNIQUE (account_id, role_id);

CREATE INDEX IF NOT EXISTS idx_account_role_account_id ON account_role(account_id);
CREATE INDEX IF NOT EXISTS idx_account_role_role_id ON account_role(role_id);
