-- Migration: 022_audit_log.sql
CREATE TABLE audit_log (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_table TEXT NOT NULL,
    entity_id BIGINT,
    operation TEXT NOT NULL,
    changed_by BIGINT REFERENCES account(account_id),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    changes JSONB,
    reference_code TEXT,
    notes TEXT,
    transaction_id UUID,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_module_created TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON audit_log(entity_table, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_at ON audit_log(changed_at);
