-- Migration: 024_material_control.sql
-- Estimating department form: Material Control
CREATE TABLE material_control (
    material_control_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES party(party_id),
    control_code TEXT NOT NULL UNIQUE,
    budget NUMERIC NOT NULL,
    total_estimated_cost NUMERIC,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    log_reviewed_by_account_id BIGINT,
    log_date_reviewed TIMESTAMPTZ,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_material_control_project_id ON material_control(project_id);
CREATE INDEX IF NOT EXISTS idx_material_control_status_id ON material_control(status_id);

CREATE TABLE material_control_item (
    material_control_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    material_control_id BIGINT NOT NULL
        REFERENCES material_control(material_control_id) ON DELETE CASCADE,

    material_id BIGINT NOT NULL
        REFERENCES material(material_id),

    estimated_quantity NUMERIC(18,4) NOT NULL,

    uom_id BIGINT NOT NULL
        REFERENCES unit_of_measure(uom_id),

    estimated_unit_cost NUMERIC(18,4),
    estimated_total_cost NUMERIC(18,4),

    remarks TEXT,
    line_no INT NOT NULL,

    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_material_control_item_control
ON material_control_item(material_control_id);

CREATE INDEX IF NOT EXISTS idx_material_control_item_material
ON material_control_item(material_id);

CREATE INDEX IF NOT EXISTS idx_material_control_item_uom
ON material_control_item(uom_id);

ALTER TABLE material_control_item
ADD CONSTRAINT uq_material_control_item_line_no
UNIQUE (material_control_id, line_no);