-- Migration: 026_material_request.sql
-- Project site material request workflow
CREATE TABLE material_request (
    material_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr_number TEXT NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES party(party_id),
    requested_by_user_id BIGINT REFERENCES "user"(user_id),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    date_prepared TIMESTAMPTZ,
    date_received TIMESTAMPTZ,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    -- `current_department` removed; workflow tracked by `status_id` and logs
    stock_checked BOOLEAN NOT NULL DEFAULT FALSE,
    ceo_approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    ceo_approved BOOLEAN,
    ceo_approved_by BIGINT REFERENCES "user"(user_id),
    ceo_approved_at TIMESTAMPTZ,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_material_request_project_id ON material_request(project_id);
CREATE INDEX IF NOT EXISTS idx_material_request_status_id ON material_request(status_id);
CREATE INDEX IF NOT EXISTS idx_material_request_requested_by_user_id ON material_request(requested_by_user_id);
