-- Migration: 027_material_request_item.sql
-- Line items for material requests; compare requested, approved and estimated quantities
CREATE TABLE material_request_item (
    material_request_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_request_id BIGINT NOT NULL REFERENCES material_request(material_request_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    requested_quantity NUMERIC NOT NULL,
    approved_quantity NUMERIC,
    estimated_quantity NUMERIC,
    area_usage TEXT,
    remarks TEXT,
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_material_request_item_request_id ON material_request_item(material_request_id);
CREATE INDEX IF NOT EXISTS idx_material_request_item_material_id ON material_request_item(material_id);
CREATE INDEX IF NOT EXISTS idx_material_request_item_uom_id ON material_request_item(uom_id);
