-- Migration: 028_additional_control.sql
-- Coordinating department adjustment form: Additional Control
CREATE TABLE additional_control (
    additional_control_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    control_code TEXT NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES party(party_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    -- Totals: estimated (from material_control), requested extra, and served/delivered
    material_control_quantity NUMERIC NOT NULL DEFAULT 0,
    additional_control_quantity NUMERIC NOT NULL DEFAULT 0,
    served_control_quantity NUMERIC NOT NULL DEFAULT 0,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    approval_method TEXT,
    approval_comment TEXT,
    approved_by BIGINT REFERENCES account(account_id),
    approved_at TIMESTAMPTZ,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

-- Ensure one aggregated row per project/material/uom
CREATE UNIQUE INDEX IF NOT EXISTS uq_additional_control_project_material_uom
    ON additional_control(project_id, material_id, uom_id);

CREATE INDEX IF NOT EXISTS idx_additional_control_project_id ON additional_control(project_id);
CREATE INDEX IF NOT EXISTS idx_additional_control_material_id ON additional_control(material_id);
CREATE INDEX IF NOT EXISTS idx_additional_control_uom_id ON additional_control(uom_id);
CREATE INDEX IF NOT EXISTS idx_additional_control_status_id ON additional_control(status_id);
