-- Migration: 030_purchase_order.sql
-- Purchasing department purchase order header table
CREATE TABLE purchase_order (
    purchase_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES party(party_id),
    material_request_id BIGINT REFERENCES material_request(material_request_id),
    supplier_party_id BIGINT NOT NULL REFERENCES party(party_id),
    requested_by_user_id BIGINT REFERENCES "user"(user_id),
    prepared_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expected_delivery_date TIMESTAMPTZ,
    order_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    total_amount NUMERIC,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_purchase_order_project_id ON purchase_order(project_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_material_request_id ON purchase_order(material_request_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_supplier_party_id ON purchase_order(supplier_party_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_requested_by_user_id ON purchase_order(requested_by_user_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_order_type_id ON purchase_order(order_type_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_status_id ON purchase_order(status_id);
