-- Migration: 031_purchase_order_item.sql
-- Purchasing department purchase order line items
CREATE TABLE purchase_order_item (
    purchase_order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order(purchase_order_id),
    material_request_item_id BIGINT REFERENCES material_request_item(material_request_item_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    requested_quantity NUMERIC NOT NULL,
    ordered_quantity NUMERIC NOT NULL,
    received_quantity NUMERIC NOT NULL DEFAULT 0,
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    unit_price NUMERIC,
    line_total NUMERIC,
    supplier_reference TEXT,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_purchase_order_item_purchase_order_id ON purchase_order_item(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_material_request_item_id ON purchase_order_item(material_request_item_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_material_id ON purchase_order_item(material_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_uom_id ON purchase_order_item(uom_id);
