-- Migration: 033_delivery_receipt_item.sql
-- Line items for warehouse delivery receipts
CREATE TABLE delivery_receipt_item (
    delivery_receipt_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_receipt_id BIGINT NOT NULL REFERENCES delivery_receipt(delivery_receipt_id),
    purchase_order_item_id BIGINT REFERENCES purchase_order_item(purchase_order_item_id),
    material_request_item_id BIGINT REFERENCES material_request_item(material_request_item_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    quantity NUMERIC NOT NULL,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_delivery_receipt_item_receipt_id ON delivery_receipt_item(delivery_receipt_id);
CREATE INDEX IF NOT EXISTS idx_delivery_receipt_item_purchase_order_item_id ON delivery_receipt_item(purchase_order_item_id);
CREATE INDEX IF NOT EXISTS idx_delivery_receipt_item_material_request_item_id ON delivery_receipt_item(material_request_item_id);
CREATE INDEX IF NOT EXISTS idx_delivery_receipt_item_material_id ON delivery_receipt_item(material_id);
CREATE INDEX IF NOT EXISTS idx_delivery_receipt_item_material_brand_id ON delivery_receipt_item(material_brand_id);
CREATE INDEX IF NOT EXISTS idx_delivery_receipt_item_uom_id ON delivery_receipt_item(uom_id);
