-- Migration: 034_delivery_advice.sql
-- Supplier delivery advice form for MPO partial deliveries
CREATE TABLE delivery_advice (
    delivery_advice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order(purchase_order_id),
    da_number TEXT NOT NULL,
    reference_code TEXT NOT NULL UNIQUE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    received_at TIMESTAMPTZ,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_advice_po_da_number ON delivery_advice(purchase_order_id, da_number);
CREATE INDEX IF NOT EXISTS idx_delivery_advice_purchase_order_id ON delivery_advice(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_delivery_advice_status_id ON delivery_advice(status_id);
