-- Migration: 035_delivery_advice_item.sql
-- Line items for supplier delivery advice documents
CREATE TABLE delivery_advice_item (
    delivery_advice_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_advice_id BIGINT NOT NULL REFERENCES delivery_advice(delivery_advice_id),
    purchase_order_item_id BIGINT REFERENCES purchase_order_item(purchase_order_item_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    advised_quantity NUMERIC NOT NULL,
    received_quantity NUMERIC NOT NULL DEFAULT 0,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_delivery_advice_item_delivery_advice_id ON delivery_advice_item(delivery_advice_id);
CREATE INDEX IF NOT EXISTS idx_delivery_advice_item_purchase_order_item_id ON delivery_advice_item(purchase_order_item_id);
CREATE INDEX IF NOT EXISTS idx_delivery_advice_item_material_id ON delivery_advice_item(material_id);
CREATE INDEX IF NOT EXISTS idx_delivery_advice_item_material_brand_id ON delivery_advice_item(material_brand_id);
CREATE INDEX IF NOT EXISTS idx_delivery_advice_item_uom_id ON delivery_advice_item(uom_id);
