-- Migration: 037_purchase_order_item_adjustment.sql
-- Item-level adjustments for purchase order items (discounts and charges)
CREATE TABLE purchase_order_item_adj (
    purchase_order_item_adj_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_item_id BIGINT NOT NULL REFERENCES purchase_order_item(purchase_order_item_id),
    adjustment_kind_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    description TEXT NOT NULL,
    adjustment_value NUMERIC NOT NULL,
    is_percentage BOOLEAN NOT NULL DEFAULT FALSE,
    sequence INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_purchase_order_item_adj_item_id ON purchase_order_item_adj(purchase_order_item_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_adj_adjustment_kind_id ON purchase_order_item_adj(adjustment_kind_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_adj_sequence ON purchase_order_item_adj(sequence);
