-- Migration: 038_stock_transfer.sql
-- Unified inventory stock transfer form for warehouse delivery/return transfers
CREATE TABLE stock_transfer (
    stock_transfer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_transfer_number TEXT NOT NULL UNIQUE,
    transfer_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    source_id BIGINT NOT NULL REFERENCES party(party_id),
    destination_id BIGINT NOT NULL REFERENCES party(party_id),
    project_id BIGINT REFERENCES party(party_id),
    purchase_order_id BIGINT REFERENCES purchase_order(purchase_order_id),
    delivery_advice_id BIGINT REFERENCES delivery_advice(delivery_advice_id),
    prepared_by_user_id BIGINT REFERENCES "user"(user_id),
    transfer_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    reference_code TEXT,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE TABLE stock_transfer_item (
    stock_transfer_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_transfer_id BIGINT NOT NULL REFERENCES stock_transfer(stock_transfer_id),
    stock_movement_id BIGINT REFERENCES stock_movement(stock_movement_id),
    purchase_order_item_id BIGINT REFERENCES purchase_order_item(purchase_order_item_id),
    material_request_item_id BIGINT REFERENCES material_request_item(material_request_item_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    quantity NUMERIC NOT NULL,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_stock_transfer_transfer_type_id ON stock_transfer(transfer_type_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_source_id ON stock_transfer(source_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_destination_id ON stock_transfer(destination_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_project_id ON stock_transfer(project_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_purchase_order_id ON stock_transfer(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_delivery_advice_id ON stock_transfer(delivery_advice_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_prepared_by_user_id ON stock_transfer(prepared_by_user_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_status_id ON stock_transfer(status_id);

CREATE INDEX IF NOT EXISTS idx_stock_transfer_item_stock_transfer_id ON stock_transfer_item(stock_transfer_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_item_stock_movement_id ON stock_transfer_item(stock_movement_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_item_purchase_order_item_id ON stock_transfer_item(purchase_order_item_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_item_material_request_item_id ON stock_transfer_item(material_request_item_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_item_material_id ON stock_transfer_item(material_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_item_material_brand_id ON stock_transfer_item(material_brand_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_item_uom_id ON stock_transfer_item(uom_id);
