-- Migration: 039_job_order.sql
-- Job order module for internal and external service work orders
CREATE TABLE job_order (
    job_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_order_number TEXT NOT NULL UNIQUE,
    service_type_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    requesting_party_id BIGINT REFERENCES party(party_id),
    service_provider_id BIGINT REFERENCES party(party_id),
    requested_by_user_id BIGINT REFERENCES "user"(user_id),
    prepared_by_user_id BIGINT REFERENCES "user"(user_id),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expected_completion_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE TABLE job_order_item (
    job_order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_order_id BIGINT NOT NULL REFERENCES job_order(job_order_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    quantity NUMERIC NOT NULL,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX IF NOT EXISTS idx_job_order_service_type_id ON job_order(service_type_id);
CREATE INDEX IF NOT EXISTS idx_job_order_requesting_party_id ON job_order(requesting_party_id);
CREATE INDEX IF NOT EXISTS idx_job_order_service_provider_id ON job_order(service_provider_id);
CREATE INDEX IF NOT EXISTS idx_job_order_requested_by_user_id ON job_order(requested_by_user_id);
CREATE INDEX IF NOT EXISTS idx_job_order_prepared_by_user_id ON job_order(prepared_by_user_id);
CREATE INDEX IF NOT EXISTS idx_job_order_status_id ON job_order(status_id);

CREATE INDEX IF NOT EXISTS idx_job_order_item_job_order_id ON job_order_item(job_order_id);
CREATE INDEX IF NOT EXISTS idx_job_order_item_material_id ON job_order_item(material_id);
CREATE INDEX IF NOT EXISTS idx_job_order_item_material_brand_id ON job_order_item(material_brand_id);
CREATE INDEX IF NOT EXISTS idx_job_order_item_uom_id ON job_order_item(uom_id);
