-- Migration: 042_physical_count.sql
-- Inventory physical count module for quarterly site audits
CREATE TABLE physical_count (
    physical_count_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    physical_count_number TEXT NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES party(party_id),
    counted_by_user_id BIGINT REFERENCES "user"(user_id),
    counted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    audit_period_start TIMESTAMPTZ,
    audit_period_end TIMESTAMPTZ,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE TABLE physical_count_item (
    physical_count_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    physical_count_id BIGINT NOT NULL REFERENCES physical_count(physical_count_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    expected_quantity NUMERIC NOT NULL,
    counted_quantity NUMERIC NOT NULL,
    variance_quantity NUMERIC NOT NULL,
    variance_reason TEXT,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

INSERT INTO look_up (
    look_up_type,
    code,
    name,
    description,
    display_order,
    log_module_created,
    log_module_updated
)
VALUES
    ('physical_count_status', 'draft', 'Draft', 'Physical count is created and has not yet been finalized.', 1, NULL, NULL),
    ('physical_count_status', 'verified', 'Verified', 'Physical count quantities have been reviewed and verified.', 2, NULL, NULL),
    ('physical_count_status', 'completed', 'Completed', 'Physical count is complete and closed.', 3, NULL, NULL)
ON CONFLICT (look_up_type, name) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_physical_count_project_id ON physical_count(project_id);
CREATE INDEX IF NOT EXISTS idx_physical_count_status_id ON physical_count(status_id);
CREATE INDEX IF NOT EXISTS idx_physical_count_item_physical_count_id ON physical_count_item(physical_count_id);
CREATE INDEX IF NOT EXISTS idx_physical_count_item_material_id ON physical_count_item(material_id);
CREATE INDEX IF NOT EXISTS idx_physical_count_item_material_brand_id ON physical_count_item(material_brand_id);
CREATE INDEX IF NOT EXISTS idx_physical_count_item_uom_id ON physical_count_item(uom_id);
