-- Migration: 043_material_adjustment.sql
-- Inventory material adjustment module for approved stock corrections
CREATE TABLE material_adjustment (
    material_adjustment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_adjustment_number TEXT NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES party(party_id),
    requested_by_user_id BIGINT REFERENCES "user"(user_id),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_by_user_id BIGINT REFERENCES "user"(user_id),
    approved_at TIMESTAMPTZ,
    status_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    adjustment_reason_id BIGINT REFERENCES look_up(look_up_id),
    notes TEXT,
    stock_movement_id BIGINT REFERENCES stock_movement(stock_movement_id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE TABLE material_adjustment_item (
    material_adjustment_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_adjustment_id BIGINT NOT NULL REFERENCES material_adjustment(material_adjustment_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    system_quantity NUMERIC NOT NULL,
    adjustment_quantity NUMERIC NOT NULL,
    resulting_quantity NUMERIC NOT NULL,
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_user_id BIGINT,
    log_updated_by_user_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_user_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

INSERT INTO look_up (
    look_up_type,
    code,
    name,
    description,
    display_order,
    log_module_created,
    log_module_updated
)
VALUES
    ('material_adjustment_status', 'pending', 'Pending', 'Adjustment request is pending approval.', 1, NULL, NULL),
    ('material_adjustment_status', 'approved', 'Approved', 'Adjustment request has been approved and is ready for posting.', 2, NULL, NULL),
    ('material_adjustment_status', 'rejected', 'Rejected', 'Adjustment request has been rejected.', 3, NULL, NULL),
    ('material_adjustment_status', 'completed', 'Completed', 'Adjustment has been applied and recorded.', 4, NULL, NULL),
    ('material_adjustment_reason', 'lost', 'Lost', 'Material lost from the site and adjusted out of stock.', 1, NULL, NULL),
    ('material_adjustment_reason', 'damaged', 'Damaged', 'Material damaged and removed from stock.', 2, NULL, NULL),
    ('material_adjustment_reason', 'theft', 'Theft', 'Material stolen or missing due to theft.', 3, NULL, NULL),
    ('material_adjustment_reason', 'other', 'Other', 'Other approved inventory adjustment reason.', 4, NULL, NULL)
ON CONFLICT (look_up_type, name) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_material_adjustment_project_id ON material_adjustment(project_id);
CREATE INDEX IF NOT EXISTS idx_material_adjustment_status_id ON material_adjustment(status_id);
CREATE INDEX IF NOT EXISTS idx_material_adjustment_approved_by_user_id ON material_adjustment(approved_by_user_id);
CREATE INDEX IF NOT EXISTS idx_material_adjustment_reason_id ON material_adjustment(adjustment_reason_id);
CREATE INDEX IF NOT EXISTS idx_material_adjustment_item_material_adjustment_id ON material_adjustment_item(material_adjustment_id);
CREATE INDEX IF NOT EXISTS idx_material_adjustment_item_material_id ON material_adjustment_item(material_id);
CREATE INDEX IF NOT EXISTS idx_material_adjustment_item_material_brand_id ON material_adjustment_item(material_brand_id);
CREATE INDEX IF NOT EXISTS idx_material_adjustment_item_uom_id ON material_adjustment_item(uom_id);
