-- Migration: 044_supplier_delivery.sql
-- Inventory Supplier Delivery module (DB layer only)

INSERT INTO look_up (
    look_up_type,
    code,
    name,
    description,
    display_order,
    log_module_created,
    log_module_updated
)
VALUES
    ('purchase_order_status', 'draft', 'Draft', 'Purchase order is created but not yet approved.', 1, NULL, NULL),
    ('purchase_order_status', 'approved', 'Approved', 'Purchase order is approved and can be received.', 2, NULL, NULL),
    ('purchase_order_status', 'partially_delivered', 'Partially Delivered', 'Purchase order has been partially delivered.', 3, NULL, NULL),
    ('purchase_order_status', 'delivered', 'Delivered', 'Purchase order has been fully delivered.', 4, NULL, NULL),
    ('purchase_order_status', 'cancelled', 'Cancelled', 'Purchase order was cancelled.', 5, NULL, NULL),
    ('supplier_delivery_status', 'draft', 'Draft', 'Supplier delivery is prepared and not yet posted.', 1, NULL, NULL),
    ('supplier_delivery_status', 'posted', 'Posted', 'Supplier delivery has been posted to inventory.', 2, NULL, NULL),
    ('supplier_delivery_status', 'cancelled', 'Cancelled', 'Supplier delivery was cancelled.', 3, NULL, NULL)
ON CONFLICT (look_up_type, name) DO NOTHING;

CREATE TABLE supplier_delivery (
    supplier_delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_delivery_number TEXT,
    reference_code TEXT,
    purchase_order_id BIGINT REFERENCES purchase_order(purchase_order_id),
    supplier_id BIGINT REFERENCES party(party_id),
    project_id BIGINT REFERENCES party(party_id),
    received_by_account_id BIGINT REFERENCES account(account_id),
    delivery_date TIMESTAMPTZ,
    status_id BIGINT REFERENCES look_up(look_up_id),
    posted_at TIMESTAMPTZ,
    posted_by_account_id BIGINT REFERENCES account(account_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT chk_supplier_delivery_distinct_parties CHECK (supplier_id <> project_id),
    CONSTRAINT chk_supplier_delivery_posted_fields CHECK (
        (posted_at IS NULL AND posted_by_account_id IS NULL)
        OR (posted_at IS NOT NULL AND posted_by_account_id IS NOT NULL)
    )
);

CREATE TABLE supplier_delivery_item (
    supplier_delivery_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_delivery_id BIGINT NOT NULL REFERENCES supplier_delivery(supplier_delivery_id),
    purchase_order_item_id BIGINT REFERENCES purchase_order_item(purchase_order_item_id),
    material_id BIGINT NOT NULL REFERENCES material(material_id),
    material_brand_id BIGINT REFERENCES material_brand(material_brand_id),
    uom_id BIGINT NOT NULL REFERENCES unit_of_measure(uom_id),
    delivered_quantity NUMERIC NOT NULL,
    accepted_quantity NUMERIC NOT NULL,
    rejected_quantity NUMERIC NOT NULL DEFAULT 0,
    stock_movement_id BIGINT REFERENCES stock_movement(stock_movement_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT chk_supplier_delivery_item_positive_delivered CHECK (delivered_quantity > 0),
    CONSTRAINT chk_supplier_delivery_item_non_negative_accepted CHECK (accepted_quantity >= 0),
    CONSTRAINT chk_supplier_delivery_item_non_negative_rejected CHECK (rejected_quantity >= 0),
    CONSTRAINT chk_supplier_delivery_item_sum_qty CHECK (accepted_quantity + rejected_quantity = delivered_quantity)
);

CREATE TABLE supplier_delivery_advice (
    supplier_delivery_advice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_delivery_id BIGINT NOT NULL REFERENCES supplier_delivery(supplier_delivery_id),
    delivery_advice_id BIGINT NOT NULL REFERENCES delivery_advice(delivery_advice_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_supplier_delivery_advice UNIQUE (supplier_delivery_id, delivery_advice_id)
);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_purchase_order_id ON supplier_delivery(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_supplier_id ON supplier_delivery(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_project_id ON supplier_delivery(project_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_status_id ON supplier_delivery(status_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_delivery_date ON supplier_delivery(delivery_date);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_item_supplier_delivery_id ON supplier_delivery_item(supplier_delivery_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_item_purchase_order_item_id ON supplier_delivery_item(purchase_order_item_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_item_material_id ON supplier_delivery_item(material_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_item_stock_movement_id ON supplier_delivery_item(stock_movement_id);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_advice_supplier_delivery_id ON supplier_delivery_advice(supplier_delivery_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_advice_delivery_advice_id ON supplier_delivery_advice(delivery_advice_id);

CREATE OR REPLACE FUNCTION validate_supplier_delivery_header()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_po_supplier_id BIGINT;
BEGIN
    SELECT supplier_party_id
    INTO v_po_supplier_id
    FROM purchase_order
    WHERE purchase_order_id = NEW.purchase_order_id
      AND is_deleted = FALSE;

    IF v_po_supplier_id IS NULL THEN
        RAISE EXCEPTION 'Purchase order % was not found or is deleted.', NEW.purchase_order_id;
    END IF;

    IF NEW.supplier_id <> v_po_supplier_id THEN
        RAISE EXCEPTION
            'Supplier party % does not match purchase order supplier % for PO %.',
            NEW.supplier_id,
            v_po_supplier_id,
            NEW.purchase_order_id;
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_validate_supplier_delivery_header
BEFORE INSERT OR UPDATE OF purchase_order_id, supplier_id
ON supplier_delivery
FOR EACH ROW
EXECUTE FUNCTION validate_supplier_delivery_header();

CREATE OR REPLACE FUNCTION validate_supplier_delivery_item()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_po_id BIGINT;
    v_poi RECORD;
BEGIN
    SELECT purchase_order_id
    INTO v_po_id
    FROM supplier_delivery
    WHERE supplier_delivery_id = NEW.supplier_delivery_id
      AND is_deleted = FALSE;

    IF v_po_id IS NULL THEN
        RAISE EXCEPTION 'Supplier delivery % was not found or is deleted.', NEW.supplier_delivery_id;
    END IF;

    SELECT purchase_order_id, material_id, uom_id
    INTO v_poi
    FROM purchase_order_item
    WHERE purchase_order_item_id = NEW.purchase_order_item_id
      AND is_deleted = FALSE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Purchase order item % was not found or is deleted.', NEW.purchase_order_item_id;
    END IF;

    IF v_poi.purchase_order_id <> v_po_id THEN
        RAISE EXCEPTION
            'Purchase order item % does not belong to purchase order % on supplier delivery %.',
            NEW.purchase_order_item_id,
            v_po_id,
            NEW.supplier_delivery_id;
    END IF;

    IF v_poi.material_id <> NEW.material_id THEN
        RAISE EXCEPTION
            'Material % on supplier delivery item does not match purchase order item material %.',
            NEW.material_id,
            v_poi.material_id;
    END IF;

    IF v_poi.uom_id <> NEW.uom_id THEN
        RAISE EXCEPTION
            'UOM % on supplier delivery item does not match purchase order item UOM %.',
            NEW.uom_id,
            v_poi.uom_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_supplier_delivery_item
BEFORE INSERT OR UPDATE OF supplier_delivery_id, purchase_order_item_id, material_id, uom_id
ON supplier_delivery_item
FOR EACH ROW
EXECUTE FUNCTION validate_supplier_delivery_item();

CREATE OR REPLACE FUNCTION validate_supplier_delivery_advice()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_sd_po_id BIGINT;
    v_da_po_id BIGINT;
BEGIN
    SELECT purchase_order_id
    INTO v_sd_po_id
    FROM supplier_delivery
    WHERE supplier_delivery_id = NEW.supplier_delivery_id
      AND is_deleted = FALSE;

    IF v_sd_po_id IS NULL THEN
        RAISE EXCEPTION 'Supplier delivery % was not found or is deleted.', NEW.supplier_delivery_id;
    END IF;

    SELECT purchase_order_id
    INTO v_da_po_id
    FROM delivery_advice
    WHERE delivery_advice_id = NEW.delivery_advice_id
      AND is_deleted = FALSE;

    IF v_da_po_id IS NULL THEN
        RAISE EXCEPTION 'Delivery advice % was not found or is deleted.', NEW.delivery_advice_id;
    END IF;

    IF v_da_po_id <> v_sd_po_id THEN
        RAISE EXCEPTION
            'Delivery advice % belongs to purchase order %, but supplier delivery % belongs to purchase order %.',
            NEW.delivery_advice_id,
            v_da_po_id,
            NEW.supplier_delivery_id,
            v_sd_po_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_supplier_delivery_advice
BEFORE INSERT OR UPDATE OF supplier_delivery_id, delivery_advice_id
ON supplier_delivery_advice
FOR EACH ROW
EXECUTE FUNCTION validate_supplier_delivery_advice();

CREATE OR REPLACE FUNCTION post_supplier_delivery(
    p_supplier_delivery_id BIGINT,
    p_posted_by_account_id BIGINT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_sd supplier_delivery%ROWTYPE;
    v_po purchase_order%ROWTYPE;
    v_item RECORD;
    v_status_draft_id BIGINT;
    v_status_posted_id BIGINT;
    v_po_status_approved_id BIGINT;
    v_po_status_partial_id BIGINT;
    v_po_status_delivered_id BIGINT;
    v_movement_type_receipt_id BIGINT;
    v_movement_status_completed_id BIGINT;
    v_remaining_qty NUMERIC;
    v_movement_id BIGINT;
    v_item_count BIGINT := 0;
    v_posted_item_count BIGINT := 0;
    v_has_remaining BOOLEAN;
BEGIN
    SELECT look_up_id
    INTO v_status_draft_id
    FROM look_up
    WHERE look_up_type = 'supplier_delivery_status'
      AND code = 'draft';

    SELECT look_up_id
    INTO v_status_posted_id
    FROM look_up
    WHERE look_up_type = 'supplier_delivery_status'
      AND code = 'posted';

    SELECT look_up_id
    INTO v_po_status_approved_id
    FROM look_up
    WHERE look_up_type = 'purchase_order_status'
      AND code = 'approved';

    SELECT look_up_id
    INTO v_po_status_partial_id
    FROM look_up
    WHERE look_up_type = 'purchase_order_status'
      AND code = 'partially_delivered';

    SELECT look_up_id
    INTO v_po_status_delivered_id
    FROM look_up
    WHERE look_up_type = 'purchase_order_status'
      AND code = 'delivered';

    SELECT look_up_id
    INTO v_movement_type_receipt_id
    FROM look_up
    WHERE look_up_type = 'stock_movement_type'
      AND code = 'receipt';

    SELECT look_up_id
    INTO v_movement_status_completed_id
    FROM look_up
    WHERE look_up_type = 'stock_movement_status'
      AND code = 'completed';

    IF v_status_draft_id IS NULL OR v_status_posted_id IS NULL THEN
        RAISE EXCEPTION 'Required supplier_delivery_status lookups are missing.';
    END IF;

    IF v_po_status_approved_id IS NULL OR v_po_status_partial_id IS NULL OR v_po_status_delivered_id IS NULL THEN
        RAISE EXCEPTION 'Required purchase_order_status lookups are missing.';
    END IF;

    IF v_movement_type_receipt_id IS NULL OR v_movement_status_completed_id IS NULL THEN
        RAISE EXCEPTION 'Required stock movement lookups are missing.';
    END IF;

    SELECT *
    INTO v_sd
    FROM supplier_delivery
    WHERE supplier_delivery_id = p_supplier_delivery_id
      AND is_deleted = FALSE
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Supplier delivery % was not found or is deleted.', p_supplier_delivery_id;
    END IF;

    IF v_sd.status_id <> v_status_draft_id THEN
        RAISE EXCEPTION 'Supplier delivery % must be in draft status before posting.', p_supplier_delivery_id;
    END IF;

    SELECT *
    INTO v_po
    FROM purchase_order
    WHERE purchase_order_id = v_sd.purchase_order_id
      AND is_deleted = FALSE
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Purchase order % was not found or is deleted.', v_sd.purchase_order_id;
    END IF;

    IF v_po.supplier_party_id <> v_sd.supplier_id THEN
        RAISE EXCEPTION
            'Supplier delivery supplier % does not match purchase order supplier %.',
            v_sd.supplier_id,
            v_po.supplier_party_id;
    END IF;

    IF v_po.status_id NOT IN (v_po_status_approved_id, v_po_status_partial_id) THEN
        RAISE EXCEPTION
            'Purchase order % is not in an approved/partially delivered status and cannot be received.',
            v_po.purchase_order_id;
    END IF;

    FOR v_item IN
        SELECT
            sdi.supplier_delivery_item_id,
            sdi.purchase_order_item_id,
            sdi.material_id,
            sdi.material_brand_id,
            sdi.uom_id,
            sdi.accepted_quantity,
            poi.purchase_order_id,
            poi.ordered_quantity,
            poi.received_quantity
        FROM supplier_delivery_item sdi
        JOIN purchase_order_item poi
          ON poi.purchase_order_item_id = sdi.purchase_order_item_id
        WHERE sdi.supplier_delivery_id = p_supplier_delivery_id
          AND sdi.is_deleted = FALSE
          AND poi.is_deleted = FALSE
        FOR UPDATE OF sdi, poi
    LOOP
        v_item_count := v_item_count + 1;

        IF v_item.purchase_order_id <> v_sd.purchase_order_id THEN
            RAISE EXCEPTION
                'Supplier delivery item % does not belong to purchase order %.',
                v_item.supplier_delivery_item_id,
                v_sd.purchase_order_id;
        END IF;

        v_remaining_qty := v_item.ordered_quantity - v_item.received_quantity;
        IF v_item.accepted_quantity > v_remaining_qty THEN
            RAISE EXCEPTION
                'Accepted quantity % exceeds remaining quantity % for PO item %.',
                v_item.accepted_quantity,
                v_remaining_qty,
                v_item.purchase_order_item_id;
        END IF;

        IF v_item.accepted_quantity > 0 THEN
            INSERT INTO stock_movement (
                source_id,
                destination_id,
                material_id,
                material_brand_id,
                quantity,
                uom_id,
                movement_type_id,
                status_id,
                movement_date,
                reference_code,
                notes,
                log_date_created,
                log_created_by_account_id,
                log_module_created
            ) VALUES (
                v_sd.supplier_id,
                v_sd.project_id,
                v_item.material_id,
                v_item.material_brand_id,
                v_item.accepted_quantity,
                v_item.uom_id,
                v_movement_type_receipt_id,
                v_movement_status_completed_id,
                COALESCE(v_sd.delivery_date, now()),
                v_sd.supplier_delivery_number,
                v_sd.notes,
                now(),
                COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                'supplier_delivery'
            ) RETURNING stock_movement_id INTO v_movement_id;

            UPDATE supplier_delivery_item
            SET stock_movement_id = v_movement_id,
                log_date_updated = now(),
                log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                log_module_updated = 'supplier_delivery'
            WHERE supplier_delivery_item_id = v_item.supplier_delivery_item_id;

            INSERT INTO stock_balance (
                party_id,
                material_id,
                material_brand_id,
                quantity_on_hand,
                uom_id,
                log_date_created,
                log_created_by_account_id,
                log_module_created
            )
            SELECT
                v_sd.project_id,
                v_item.material_id,
                v_item.material_brand_id,
                0,
                v_item.uom_id,
                now(),
                COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                'supplier_delivery'
            WHERE NOT EXISTS (
                SELECT 1
                FROM stock_balance sb
                WHERE sb.party_id = v_sd.project_id
                  AND sb.material_id = v_item.material_id
                  AND sb.uom_id = v_item.uom_id
                  AND (
                      (sb.material_brand_id IS NULL AND v_item.material_brand_id IS NULL)
                      OR sb.material_brand_id = v_item.material_brand_id
                  )
            );

            UPDATE stock_balance
            SET quantity_on_hand = quantity_on_hand + v_item.accepted_quantity,
                log_date_updated = now(),
                log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                log_module_updated = 'supplier_delivery'
            WHERE party_id = v_sd.project_id
              AND material_id = v_item.material_id
              AND uom_id = v_item.uom_id
              AND (
                  (material_brand_id IS NULL AND v_item.material_brand_id IS NULL)
                  OR material_brand_id = v_item.material_brand_id
              );

            INSERT INTO stock_layer (
                party_id,
                material_id,
                material_brand_id,
                uom_id,
                quantity_received,
                quantity_available,
                receive_date,
                source_movement_id,
                log_date_created,
                log_created_by_account_id,
                log_module_created
            ) VALUES (
                v_sd.project_id,
                v_item.material_id,
                v_item.material_brand_id,
                v_item.uom_id,
                v_item.accepted_quantity,
                v_item.accepted_quantity,
                COALESCE(v_sd.delivery_date, now()),
                v_movement_id,
                now(),
                COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                'supplier_delivery'
            );

            UPDATE purchase_order_item
            SET received_quantity = received_quantity + v_item.accepted_quantity,
                log_date_updated = now(),
                log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                log_module_updated = 'supplier_delivery'
            WHERE purchase_order_item_id = v_item.purchase_order_item_id;

            v_posted_item_count := v_posted_item_count + 1;
        END IF;
    END LOOP;

    IF v_item_count = 0 THEN
        RAISE EXCEPTION 'Supplier delivery % has no active line items to post.', p_supplier_delivery_id;
    END IF;

    IF v_posted_item_count = 0 THEN
        RAISE EXCEPTION 'Supplier delivery % has no accepted quantities to post.', p_supplier_delivery_id;
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM purchase_order_item poi
        WHERE poi.purchase_order_id = v_sd.purchase_order_id
          AND poi.is_deleted = FALSE
          AND poi.received_quantity < poi.ordered_quantity
    )
    INTO v_has_remaining;

    UPDATE purchase_order
    SET status_id = CASE WHEN v_has_remaining THEN v_po_status_partial_id ELSE v_po_status_delivered_id END,
        log_date_updated = now(),
        log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
        log_module_updated = 'supplier_delivery'
    WHERE purchase_order_id = v_sd.purchase_order_id;

    UPDATE supplier_delivery
    SET status_id = v_status_posted_id,
        posted_at = now(),
        posted_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
        log_date_updated = now(),
        log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
        log_module_updated = 'supplier_delivery'
    WHERE supplier_delivery_id = p_supplier_delivery_id;

    RETURN p_supplier_delivery_id;
END;
$$;