-- Migration: 046_report_catalog.sql
-- Purpose: Create the report_catalog table to manage report definitions
-- Author: MMS
-- Created: 2026-07-28

CREATE TABLE report_catalog (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_category_lookup_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    report_type_lookup_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    report_code VARCHAR(20) NOT NULL UNIQUE,
    report_name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    report_url VARCHAR(255),
    report_file VARCHAR(255),
    display_order INTEGER NOT NULL DEFAULT 0,
    requires_parameter BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    log_created_by_account_id BIGINT,
    log_date_updated TIMESTAMPTZ,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

-- Foreign key constraints
ALTER TABLE report_catalog
    ADD CONSTRAINT fk_report_catalog_report_category_lookup_id
        FOREIGN KEY (report_category_lookup_id) REFERENCES look_up(look_up_id),
    ADD CONSTRAINT fk_report_catalog_report_type_lookup_id
        FOREIGN KEY (report_type_lookup_id) REFERENCES look_up(look_up_id);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_report_catalog_report_category_lookup_id ON report_catalog(report_category_lookup_id);
CREATE INDEX IF NOT EXISTS idx_report_catalog_report_type_lookup_id ON report_catalog(report_type_lookup_id);
CREATE INDEX IF NOT EXISTS idx_report_catalog_report_code ON report_catalog(report_code);
CREATE INDEX IF NOT EXISTS idx_report_catalog_is_active ON report_catalog(is_active);
CREATE INDEX IF NOT EXISTS idx_report_catalog_is_deleted ON report_catalog(is_deleted);

-- Comments
COMMENT ON TABLE report_catalog IS 'Stores report definitions including metadata, file locations, and parameter requirements';
COMMENT ON COLUMN report_catalog.report_code IS 'Unique report code identifier (e.g., INV001, PUR001)';
COMMENT ON COLUMN report_catalog.report_name IS 'User-friendly report name';
COMMENT ON COLUMN report_catalog.requires_parameter IS 'Indicates whether this report requires parameters to be provided';
COMMENT ON COLUMN report_catalog.is_active IS 'Soft delete flag for active status';
COMMENT ON COLUMN report_catalog.is_deleted IS 'Soft delete flag';
