-- Migration: 047_report_parameter.sql
-- Purpose: Create the report_parameter table to manage report parameters
-- Author: MMS
-- Created: 2026-07-28

CREATE TABLE report_parameter (
    report_parameter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES report_catalog(report_id) ON DELETE CASCADE,
    parameter_name VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    data_type_lookup_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    control_type_lookup_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    lookup_table VARCHAR(100),
    default_value VARCHAR(255),
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    log_created_by_account_id BIGINT,
    log_date_updated TIMESTAMPTZ,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

-- Foreign key constraints
ALTER TABLE report_parameter
    ADD CONSTRAINT fk_report_parameter_report_id
        FOREIGN KEY (report_id) REFERENCES report_catalog(report_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_report_parameter_data_type_lookup_id
        FOREIGN KEY (data_type_lookup_id) REFERENCES look_up(look_up_id),
    ADD CONSTRAINT fk_report_parameter_control_type_lookup_id
        FOREIGN KEY (control_type_lookup_id) REFERENCES look_up(look_up_id);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_report_parameter_report_id ON report_parameter(report_id);
CREATE INDEX IF NOT EXISTS idx_report_parameter_data_type_lookup_id ON report_parameter(data_type_lookup_id);
CREATE INDEX IF NOT EXISTS idx_report_parameter_control_type_lookup_id ON report_parameter(control_type_lookup_id);
CREATE INDEX IF NOT EXISTS idx_report_parameter_is_deleted ON report_parameter(is_deleted);

-- Comments
COMMENT ON TABLE report_parameter IS 'Stores parameter definitions for reports, including data types and UI control types';
COMMENT ON COLUMN report_parameter.parameter_name IS 'Internal parameter name used in report queries';
COMMENT ON COLUMN report_parameter.display_name IS 'User-friendly parameter label for UI display';
COMMENT ON COLUMN report_parameter.lookup_table IS 'Optional reference table for dropdown/select controls';
COMMENT ON COLUMN report_parameter.is_required IS 'Whether this parameter must be provided before report execution';
