-- Migration: 049_report_history.sql
-- Purpose: Create the report_history table to track report execution and generation
-- Author: MMS
-- Created: 2026-07-28

CREATE TABLE report_history (
    report_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES report_catalog(report_id),
    account_id BIGINT NOT NULL REFERENCES account(account_id),
    parameters JSONB,
    generated_file VARCHAR(255),
    execution_time_ms INTEGER,
    status_lookup_id BIGINT REFERENCES look_up(look_up_id),
    log_date_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Foreign key constraints
ALTER TABLE report_history
    ADD CONSTRAINT fk_report_history_report_id
        FOREIGN KEY (report_id) REFERENCES report_catalog(report_id),
    ADD CONSTRAINT fk_report_history_account_id
        FOREIGN KEY (account_id) REFERENCES account(account_id),
    ADD CONSTRAINT fk_report_history_status_lookup_id
        FOREIGN KEY (status_lookup_id) REFERENCES look_up(look_up_id);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_report_history_report_id ON report_history(report_id);
CREATE INDEX IF NOT EXISTS idx_report_history_account_id ON report_history(account_id);
CREATE INDEX IF NOT EXISTS idx_report_history_status_lookup_id ON report_history(status_lookup_id);
CREATE INDEX IF NOT EXISTS idx_report_history_log_date_created ON report_history(log_date_created);

-- Comments
COMMENT ON TABLE report_history IS 'Audit trail for report generation and execution history';
COMMENT ON COLUMN report_history.parameters IS 'JSON object containing report execution parameters';
COMMENT ON COLUMN report_history.generated_file IS 'File path or reference to the generated report output';
COMMENT ON COLUMN report_history.execution_time_ms IS 'Report execution duration in milliseconds';
COMMENT ON COLUMN report_history.status_lookup_id IS 'Reference to report status (Success, Failed, Running)';
