-- Migration: 049_navigation.sql
-- Purpose: Create navigation system tables for database-driven menu management
-- Author: MMS
-- Created: 2026-07-28

CREATE TABLE navigation (
    navigation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_navigation_id BIGINT,
    context VARCHAR(50) NOT NULL,
    navigation_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    route VARCHAR(255),
    icon VARCHAR(100),
    permission_code VARCHAR(100),
    display_order INTEGER NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    reference_type VARCHAR(50) NOT NULL DEFAULT 'NONE',
    reference_id BIGINT,
    log_created_by_account_id BIGINT,
    log_date_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    log_updated_by_account_id BIGINT,
    log_date_updated TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_module_created TEXT,
    log_module_updated TEXT
);

ALTER TABLE navigation
    ADD CONSTRAINT fk_navigation_parent_navigation_id
        FOREIGN KEY (parent_navigation_id) REFERENCES navigation(navigation_id);

CREATE INDEX idx_navigation_parent_navigation_id ON navigation(parent_navigation_id);
CREATE INDEX idx_navigation_context ON navigation(context);
CREATE INDEX idx_navigation_context_parent ON navigation(context, parent_navigation_id) WHERE is_deleted = false;
CREATE INDEX idx_navigation_route ON navigation(route);
CREATE INDEX idx_navigation_permission_code ON navigation(permission_code);
CREATE INDEX idx_navigation_is_visible ON navigation(is_visible);
CREATE INDEX idx_navigation_is_deleted ON navigation(is_deleted);
CREATE INDEX idx_navigation_reference_type_id ON navigation(reference_type, reference_id);

COMMENT ON TABLE navigation IS 'Database-driven navigation system supporting multiple contexts (MAIN, REPORTS) with hierarchical menu structures';
COMMENT ON COLUMN navigation.context IS 'Navigation context: MAIN or REPORTS';
COMMENT ON COLUMN navigation.navigation_type IS 'Type of navigation item: GROUP, MENU, REPORT, HEADER';
COMMENT ON COLUMN navigation.permission_code IS 'Permission code required to view this menu item (if null, no permission check required)';
COMMENT ON COLUMN navigation.reference_type IS 'Type of reference: NONE or REPORT (for report catalog integration)';
COMMENT ON COLUMN navigation.reference_id IS 'ID of referenced object (e.g., report_id from report_catalog)';
