-- Migration: 051_supplier_business_hours.sql
-- Purpose: Normalize supplier business hours into a weekly schedule table
-- Author: MMS
-- Created: 2026-07-30

CREATE TABLE IF NOT EXISTS supplier_business_hours (
    supplier_business_hours_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES party(party_id),
    day_of_week SMALLINT NOT NULL,
    opening_time TIME,
    closing_time TIME,
    is_closed BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT chk_supplier_business_hours_day
        CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT chk_supplier_business_hours_time_window
        CHECK (
            (is_closed = TRUE AND opening_time IS NULL AND closing_time IS NULL)
            OR
            (is_closed = FALSE AND opening_time IS NOT NULL AND closing_time IS NOT NULL AND opening_time < closing_time)
        )
);

CREATE INDEX IF NOT EXISTS idx_supplier_business_hours_supplier_id
    ON supplier_business_hours(supplier_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_supplier_business_hours_supplier_day_active
    ON supplier_business_hours(supplier_id, day_of_week)
    WHERE is_deleted = FALSE;