-- Adds normalized material type master data and links it to material records.

CREATE TABLE IF NOT EXISTS material_type (
    material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME material_type_id_seq
    ) PRIMARY KEY,
    material_type_code TEXT,
    material_type_name TEXT NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

ALTER TABLE material
    ADD COLUMN IF NOT EXISTS material_type_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_material_material_type_id'
          AND conrelid = 'public.material'::regclass
    ) THEN
        ALTER TABLE material
            ADD CONSTRAINT fk_material_material_type_id
            FOREIGN KEY (material_type_id)
            REFERENCES material_type(material_type_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_material_material_type_id
    ON material(material_type_id);
