-- Migration: 053_system_settings.sql
-- Purpose: Create database-driven system settings and setting category tables

CREATE TABLE system_setting_category (
    system_setting_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(100) NOT NULL UNIQUE,
    category_name VARCHAR(255) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT
);

CREATE INDEX idx_system_setting_category_code ON system_setting_category(category_code);
CREATE INDEX idx_system_setting_category_display_order ON system_setting_category(display_order);

CREATE TABLE system_setting (
    system_setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_setting_category_id BIGINT NOT NULL REFERENCES system_setting_category(system_setting_category_id),
    setting_key VARCHAR(150) NOT NULL,
    setting_name VARCHAR(255) NOT NULL,
    description TEXT,
    setting_type VARCHAR(50) NOT NULL,
    setting_value TEXT,
    default_value TEXT,
    options_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    validation_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_editable BOOLEAN NOT NULL DEFAULT TRUE,
    is_resettable BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_system_setting_category_key UNIQUE (system_setting_category_id, setting_key)
);

CREATE INDEX idx_system_setting_category_id ON system_setting(system_setting_category_id);
CREATE INDEX idx_system_setting_key ON system_setting(setting_key);
CREATE INDEX idx_system_setting_display_order ON system_setting(display_order);
