-- Migration: 056_supplier_delivery_multi_source.sql
-- Refactor supplier delivery to support multi-source receiving and item-level traceability.

INSERT INTO look_up (
    look_up_type,
    code,
    name,
    description,
    display_order,
    log_module_created,
    log_module_updated
)
VALUES
    ('supplier_delivery_reference_type', 'po', 'Purchase Order', 'Reference to purchase order lines.', 1, NULL, NULL),
    ('supplier_delivery_reference_type', 'delivery_advice', 'Delivery Advice', 'Reference to delivery advice lines.', 2, NULL, NULL),
    ('supplier_delivery_reference_type', 'material_request', 'Material Request', 'Reference to material request lines.', 3, NULL, NULL)
ON CONFLICT (look_up_type, name) DO NOTHING;

DROP TRIGGER IF EXISTS trg_validate_supplier_delivery_header ON supplier_delivery;
DROP TRIGGER IF EXISTS trg_validate_supplier_delivery_item ON supplier_delivery_item;
DROP TRIGGER IF EXISTS trg_validate_supplier_delivery_advice ON supplier_delivery_advice;
DROP FUNCTION IF EXISTS validate_supplier_delivery_header();
DROP FUNCTION IF EXISTS validate_supplier_delivery_item();
DROP FUNCTION IF EXISTS validate_supplier_delivery_advice();

CREATE TABLE IF NOT EXISTS supplier_delivery_purchase_order (
    supplier_delivery_purchase_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_delivery_id BIGINT NOT NULL REFERENCES supplier_delivery(supplier_delivery_id),
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order(purchase_order_id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_supplier_delivery_purchase_order UNIQUE (supplier_delivery_id, purchase_order_id)
);

CREATE TABLE IF NOT EXISTS supplier_delivery_delivery_advice (
    supplier_delivery_delivery_advice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_delivery_id BIGINT NOT NULL REFERENCES supplier_delivery(supplier_delivery_id),
    delivery_advice_id BIGINT NOT NULL REFERENCES delivery_advice(delivery_advice_id),
    notes TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_supplier_delivery_delivery_advice UNIQUE (supplier_delivery_id, delivery_advice_id)
);

CREATE TABLE IF NOT EXISTS supplier_delivery_material_request (
    supplier_delivery_material_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_delivery_id BIGINT NOT NULL REFERENCES supplier_delivery(supplier_delivery_id),
    material_request_id BIGINT NOT NULL REFERENCES material_request(material_request_id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT uq_supplier_delivery_material_request UNIQUE (supplier_delivery_id, material_request_id)
);

CREATE TABLE IF NOT EXISTS supplier_delivery_item_reference (
    supplier_delivery_item_reference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_delivery_item_id BIGINT NOT NULL REFERENCES supplier_delivery_item(supplier_delivery_item_id),
    reference_type_lookup_id BIGINT NOT NULL REFERENCES look_up(look_up_id),
    reference_id BIGINT NOT NULL,
    reference_line_id BIGINT NOT NULL,
    quantity NUMERIC NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    log_date_created TIMESTAMPTZ,
    log_date_updated TIMESTAMPTZ,
    log_created_by_account_id BIGINT,
    log_updated_by_account_id BIGINT,
    log_date_deleted TIMESTAMPTZ,
    log_deleted_by_account_id BIGINT,
    log_module_created TEXT,
    log_module_updated TEXT,
    CONSTRAINT chk_supplier_delivery_item_reference_qty_positive CHECK (quantity > 0),
    CONSTRAINT uq_supplier_delivery_item_reference UNIQUE (
        supplier_delivery_item_id,
        reference_type_lookup_id,
        reference_id,
        reference_line_id
    )
);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_purchase_order_supplier_delivery_id
    ON supplier_delivery_purchase_order(supplier_delivery_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_purchase_order_purchase_order_id
    ON supplier_delivery_purchase_order(purchase_order_id);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_delivery_advice_supplier_delivery_id
    ON supplier_delivery_delivery_advice(supplier_delivery_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_delivery_advice_delivery_advice_id
    ON supplier_delivery_delivery_advice(delivery_advice_id);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_material_request_supplier_delivery_id
    ON supplier_delivery_material_request(supplier_delivery_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_material_request_material_request_id
    ON supplier_delivery_material_request(material_request_id);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_item_reference_item_id
    ON supplier_delivery_item_reference(supplier_delivery_item_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_item_reference_ref_type
    ON supplier_delivery_item_reference(reference_type_lookup_id, reference_id, reference_line_id);

INSERT INTO supplier_delivery_purchase_order (
    supplier_delivery_id,
    purchase_order_id,
    is_deleted,
    log_date_created,
    log_date_updated,
    log_created_by_account_id,
    log_updated_by_account_id,
    log_date_deleted,
    log_deleted_by_account_id,
    log_module_created,
    log_module_updated
)
SELECT
    sd.supplier_delivery_id,
    sd.purchase_order_id,
    sd.is_deleted,
    sd.log_date_created,
    sd.log_date_updated,
    sd.log_created_by_account_id,
    sd.log_updated_by_account_id,
    sd.log_date_deleted,
    sd.log_deleted_by_account_id,
    sd.log_module_created,
    sd.log_module_updated
FROM supplier_delivery sd
WHERE sd.purchase_order_id IS NOT NULL
ON CONFLICT (supplier_delivery_id, purchase_order_id) DO NOTHING;

INSERT INTO supplier_delivery_delivery_advice (
    supplier_delivery_id,
    delivery_advice_id,
    notes,
    is_deleted,
    log_date_created,
    log_date_updated,
    log_created_by_account_id,
    log_updated_by_account_id,
    log_date_deleted,
    log_deleted_by_account_id,
    log_module_created,
    log_module_updated
)
SELECT
    sda.supplier_delivery_id,
    sda.delivery_advice_id,
    sda.notes,
    sda.is_deleted,
    sda.log_date_created,
    sda.log_date_updated,
    sda.log_created_by_account_id,
    sda.log_updated_by_account_id,
    sda.log_date_deleted,
    sda.log_deleted_by_account_id,
    sda.log_module_created,
    sda.log_module_updated
FROM supplier_delivery_advice sda
ON CONFLICT (supplier_delivery_id, delivery_advice_id) DO NOTHING;

INSERT INTO supplier_delivery_item_reference (
    supplier_delivery_item_id,
    reference_type_lookup_id,
    reference_id,
    reference_line_id,
    quantity,
    is_deleted,
    log_date_created,
    log_date_updated,
    log_created_by_account_id,
    log_updated_by_account_id,
    log_date_deleted,
    log_deleted_by_account_id,
    log_module_created,
    log_module_updated
)
SELECT
    sdi.supplier_delivery_item_id,
    rt.look_up_id,
    poi.purchase_order_id,
    sdi.purchase_order_item_id,
    sdi.accepted_quantity,
    sdi.is_deleted,
    sdi.log_date_created,
    sdi.log_date_updated,
    sdi.log_created_by_account_id,
    sdi.log_updated_by_account_id,
    sdi.log_date_deleted,
    sdi.log_deleted_by_account_id,
    sdi.log_module_created,
    sdi.log_module_updated
FROM supplier_delivery_item sdi
JOIN purchase_order_item poi ON poi.purchase_order_item_id = sdi.purchase_order_item_id
JOIN look_up rt ON rt.look_up_type = 'supplier_delivery_reference_type' AND rt.code = 'po'
WHERE sdi.purchase_order_item_id IS NOT NULL
  AND sdi.accepted_quantity > 0
ON CONFLICT (supplier_delivery_item_id, reference_type_lookup_id, reference_id, reference_line_id) DO NOTHING;

ALTER TABLE supplier_delivery_item DROP CONSTRAINT IF EXISTS trg_validate_supplier_delivery_item;
DROP INDEX IF EXISTS idx_supplier_delivery_item_purchase_order_item_id;
ALTER TABLE supplier_delivery_item DROP COLUMN IF EXISTS purchase_order_item_id;

DROP TABLE IF EXISTS supplier_delivery_advice;
DROP INDEX IF EXISTS idx_supplier_delivery_advice_supplier_delivery_id;
DROP INDEX IF EXISTS idx_supplier_delivery_advice_delivery_advice_id;

DROP INDEX IF EXISTS idx_supplier_delivery_purchase_order_id;
ALTER TABLE supplier_delivery DROP COLUMN IF EXISTS purchase_order_id;

CREATE OR REPLACE FUNCTION validate_supplier_delivery_purchase_order()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_po RECORD;
    v_sd RECORD;
BEGIN
    SELECT supplier_party_id, project_id
    INTO v_po
    FROM purchase_order
    WHERE purchase_order_id = NEW.purchase_order_id
      AND is_deleted = FALSE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Purchase order % was not found or is deleted.', NEW.purchase_order_id;
    END IF;

    SELECT supplier_id, project_id
    INTO v_sd
    FROM supplier_delivery
    WHERE supplier_delivery_id = NEW.supplier_delivery_id
      AND is_deleted = FALSE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Supplier delivery % was not found or is deleted.', NEW.supplier_delivery_id;
    END IF;

    IF v_po.supplier_party_id <> v_sd.supplier_id THEN
        RAISE EXCEPTION
            'Supplier delivery supplier % does not match purchase order supplier %.',
            v_sd.supplier_id,
            v_po.supplier_party_id;
    END IF;

    IF v_po.project_id <> v_sd.project_id THEN
        RAISE EXCEPTION
            'Supplier delivery project % does not match purchase order project %.',
            v_sd.project_id,
            v_po.project_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_supplier_delivery_delivery_advice()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_da RECORD;
    v_po RECORD;
    v_sd RECORD;
BEGIN
    SELECT purchase_order_id
    INTO v_da
    FROM delivery_advice
    WHERE delivery_advice_id = NEW.delivery_advice_id
      AND is_deleted = FALSE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Delivery advice % was not found or is deleted.', NEW.delivery_advice_id;
    END IF;

    SELECT supplier_party_id, project_id
    INTO v_po
    FROM purchase_order
    WHERE purchase_order_id = v_da.purchase_order_id
      AND is_deleted = FALSE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Purchase order % for delivery advice % was not found or is deleted.', v_da.purchase_order_id, NEW.delivery_advice_id;
    END IF;

    SELECT supplier_id, project_id
    INTO v_sd
    FROM supplier_delivery
    WHERE supplier_delivery_id = NEW.supplier_delivery_id
      AND is_deleted = FALSE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Supplier delivery % was not found or is deleted.', NEW.supplier_delivery_id;
    END IF;

    IF v_po.supplier_party_id <> v_sd.supplier_id THEN
        RAISE EXCEPTION
            'Supplier delivery supplier % does not match delivery advice supplier %.',
            v_sd.supplier_id,
            v_po.supplier_party_id;
    END IF;

    IF v_po.project_id <> v_sd.project_id THEN
        RAISE EXCEPTION
            'Supplier delivery project % does not match delivery advice project %.',
            v_sd.project_id,
            v_po.project_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_supplier_delivery_material_request()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_mr_project_id BIGINT;
    v_sd_project_id BIGINT;
BEGIN
    SELECT project_id
    INTO v_mr_project_id
    FROM material_request
    WHERE material_request_id = NEW.material_request_id
      AND is_deleted = FALSE;

    IF v_mr_project_id IS NULL THEN
        RAISE EXCEPTION 'Material request % was not found or is deleted.', NEW.material_request_id;
    END IF;

    SELECT project_id
    INTO v_sd_project_id
    FROM supplier_delivery
    WHERE supplier_delivery_id = NEW.supplier_delivery_id
      AND is_deleted = FALSE;

    IF v_sd_project_id IS NULL THEN
        RAISE EXCEPTION 'Supplier delivery % was not found or is deleted.', NEW.supplier_delivery_id;
    END IF;

    IF v_mr_project_id <> v_sd_project_id THEN
        RAISE EXCEPTION
            'Supplier delivery project % does not match material request project %.',
            v_sd_project_id,
            v_mr_project_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_supplier_delivery_item_reference()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_ref_type_code TEXT;
    v_item RECORD;
    v_po_item RECORD;
    v_da_item RECORD;
    v_mr_item RECORD;
BEGIN
    SELECT rt.code
    INTO v_ref_type_code
    FROM look_up rt
    WHERE rt.look_up_id = NEW.reference_type_lookup_id
      AND rt.look_up_type = 'supplier_delivery_reference_type'
      AND rt.is_deleted = FALSE;

    IF v_ref_type_code IS NULL THEN
        RAISE EXCEPTION 'Reference type lookup % is invalid.', NEW.reference_type_lookup_id;
    END IF;

    SELECT
        sdi.supplier_delivery_item_id,
        sdi.material_id,
        sdi.uom_id,
        sdi.supplier_delivery_id
    INTO v_item
    FROM supplier_delivery_item sdi
    WHERE sdi.supplier_delivery_item_id = NEW.supplier_delivery_item_id
      AND sdi.is_deleted = FALSE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Supplier delivery item % was not found or is deleted.', NEW.supplier_delivery_item_id;
    END IF;

    IF v_ref_type_code = 'po' THEN
        SELECT purchase_order_id, material_id, uom_id
        INTO v_po_item
        FROM purchase_order_item
        WHERE purchase_order_item_id = NEW.reference_line_id
          AND is_deleted = FALSE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Purchase order item % was not found or is deleted.', NEW.reference_line_id;
        END IF;

        IF v_po_item.purchase_order_id <> NEW.reference_id THEN
            RAISE EXCEPTION 'PO reference line % does not belong to purchase order %.', NEW.reference_line_id, NEW.reference_id;
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM supplier_delivery_purchase_order sdpo
            WHERE sdpo.supplier_delivery_id = v_item.supplier_delivery_id
              AND sdpo.purchase_order_id = NEW.reference_id
              AND sdpo.is_deleted = FALSE
        ) THEN
            RAISE EXCEPTION 'Purchase order % is not linked to supplier delivery %.', NEW.reference_id, v_item.supplier_delivery_id;
        END IF;

        IF v_po_item.material_id <> v_item.material_id THEN
            RAISE EXCEPTION 'PO reference material does not match supplier delivery item material.';
        END IF;

        IF v_po_item.uom_id <> v_item.uom_id THEN
            RAISE EXCEPTION 'PO reference UOM does not match supplier delivery item UOM.';
        END IF;

    ELSIF v_ref_type_code = 'delivery_advice' THEN
        SELECT delivery_advice_id, material_id, uom_id
        INTO v_da_item
        FROM delivery_advice_item
        WHERE delivery_advice_item_id = NEW.reference_line_id
          AND is_deleted = FALSE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Delivery advice item % was not found or is deleted.', NEW.reference_line_id;
        END IF;

        IF v_da_item.delivery_advice_id <> NEW.reference_id THEN
            RAISE EXCEPTION 'Delivery advice reference line % does not belong to delivery advice %.', NEW.reference_line_id, NEW.reference_id;
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM supplier_delivery_delivery_advice sdda
            WHERE sdda.supplier_delivery_id = v_item.supplier_delivery_id
              AND sdda.delivery_advice_id = NEW.reference_id
              AND sdda.is_deleted = FALSE
        ) THEN
            RAISE EXCEPTION 'Delivery advice % is not linked to supplier delivery %.', NEW.reference_id, v_item.supplier_delivery_id;
        END IF;

        IF v_da_item.material_id <> v_item.material_id THEN
            RAISE EXCEPTION 'Delivery advice reference material does not match supplier delivery item material.';
        END IF;

        IF v_da_item.uom_id <> v_item.uom_id THEN
            RAISE EXCEPTION 'Delivery advice reference UOM does not match supplier delivery item UOM.';
        END IF;

    ELSIF v_ref_type_code = 'material_request' THEN
        SELECT material_request_id, material_id, uom_id
        INTO v_mr_item
        FROM material_request_item
        WHERE material_request_item_id = NEW.reference_line_id
          AND is_deleted = FALSE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Material request item % was not found or is deleted.', NEW.reference_line_id;
        END IF;

        IF v_mr_item.material_request_id <> NEW.reference_id THEN
            RAISE EXCEPTION 'Material request reference line % does not belong to material request %.', NEW.reference_line_id, NEW.reference_id;
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM supplier_delivery_material_request sdmr
            WHERE sdmr.supplier_delivery_id = v_item.supplier_delivery_id
              AND sdmr.material_request_id = NEW.reference_id
              AND sdmr.is_deleted = FALSE
        ) THEN
            RAISE EXCEPTION 'Material request % is not linked to supplier delivery %.', NEW.reference_id, v_item.supplier_delivery_id;
        END IF;

        IF v_mr_item.material_id <> v_item.material_id THEN
            RAISE EXCEPTION 'Material request reference material does not match supplier delivery item material.';
        END IF;

        IF v_mr_item.uom_id <> v_item.uom_id THEN
            RAISE EXCEPTION 'Material request reference UOM does not match supplier delivery item UOM.';
        END IF;

    ELSE
        RAISE EXCEPTION 'Unsupported reference type code %.', v_ref_type_code;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_supplier_delivery_purchase_order
BEFORE INSERT OR UPDATE OF supplier_delivery_id, purchase_order_id
ON supplier_delivery_purchase_order
FOR EACH ROW
EXECUTE FUNCTION validate_supplier_delivery_purchase_order();

CREATE TRIGGER trg_validate_supplier_delivery_delivery_advice
BEFORE INSERT OR UPDATE OF supplier_delivery_id, delivery_advice_id
ON supplier_delivery_delivery_advice
FOR EACH ROW
EXECUTE FUNCTION validate_supplier_delivery_delivery_advice();

CREATE TRIGGER trg_validate_supplier_delivery_material_request
BEFORE INSERT OR UPDATE OF supplier_delivery_id, material_request_id
ON supplier_delivery_material_request
FOR EACH ROW
EXECUTE FUNCTION validate_supplier_delivery_material_request();

CREATE TRIGGER trg_validate_supplier_delivery_item_reference
BEFORE INSERT OR UPDATE OF supplier_delivery_item_id, reference_type_lookup_id, reference_id, reference_line_id
ON supplier_delivery_item_reference
FOR EACH ROW
EXECUTE FUNCTION validate_supplier_delivery_item_reference();

CREATE OR REPLACE FUNCTION post_supplier_delivery(
    p_supplier_delivery_id BIGINT,
    p_posted_by_account_id BIGINT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_sd supplier_delivery%ROWTYPE;
    v_item RECORD;
    v_reference RECORD;
    v_status_draft_id BIGINT;
    v_status_posted_id BIGINT;
    v_po_status_partial_id BIGINT;
    v_po_status_delivered_id BIGINT;
    v_da_status_completed_id BIGINT;
    v_mr_status_completed_id BIGINT;
    v_movement_type_receipt_id BIGINT;
    v_movement_status_completed_id BIGINT;
    v_reference_sum NUMERIC;
    v_remaining_qty NUMERIC;
    v_movement_id BIGINT;
    v_item_count BIGINT := 0;
    v_posted_item_count BIGINT := 0;
    v_has_remaining BOOLEAN;
    v_po_id BIGINT;
    v_da_id BIGINT;
    v_mr_id BIGINT;
    v_posted_received_qty NUMERIC;
BEGIN
    SELECT look_up_id INTO v_status_draft_id
    FROM look_up
    WHERE look_up_type = 'supplier_delivery_status'
      AND code = 'draft';

    SELECT look_up_id INTO v_status_posted_id
    FROM look_up
    WHERE look_up_type = 'supplier_delivery_status'
      AND code = 'posted';

    SELECT look_up_id INTO v_po_status_partial_id
    FROM look_up
    WHERE look_up_type = 'purchase_order_status'
      AND code = 'partially_delivered';

    SELECT look_up_id INTO v_po_status_delivered_id
    FROM look_up
    WHERE look_up_type = 'purchase_order_status'
      AND code = 'delivered';

    SELECT look_up_id INTO v_da_status_completed_id
    FROM look_up
    WHERE look_up_type = 'delivery_advice_status'
      AND code = 'completed';

    SELECT look_up_id INTO v_mr_status_completed_id
    FROM look_up
    WHERE look_up_type = 'material_request_status'
      AND code = 'completed';

    SELECT look_up_id INTO v_movement_type_receipt_id
    FROM look_up
    WHERE look_up_type = 'stock_movement_type'
      AND code = 'receipt';

    SELECT look_up_id INTO v_movement_status_completed_id
    FROM look_up
    WHERE look_up_type = 'stock_movement_status'
      AND code = 'completed';

    IF v_status_draft_id IS NULL OR v_status_posted_id IS NULL THEN
        RAISE EXCEPTION 'Required supplier_delivery_status lookups are missing.';
    END IF;

    IF v_po_status_partial_id IS NULL OR v_po_status_delivered_id IS NULL THEN
        RAISE EXCEPTION 'Required purchase_order_status lookups are missing.';
    END IF;

    IF v_movement_type_receipt_id IS NULL OR v_movement_status_completed_id IS NULL THEN
        RAISE EXCEPTION 'Required stock movement lookups are missing.';
    END IF;

    SELECT *
    INTO v_sd
    FROM supplier_delivery
    WHERE supplier_delivery_id = p_supplier_delivery_id
      AND is_deleted = FALSE
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Supplier delivery % was not found or is deleted.', p_supplier_delivery_id;
    END IF;

    IF v_sd.status_id <> v_status_draft_id THEN
        RAISE EXCEPTION 'Supplier delivery % must be in draft status before posting.', p_supplier_delivery_id;
    END IF;

    FOR v_item IN
        SELECT
            sdi.supplier_delivery_item_id,
            sdi.material_id,
            sdi.material_brand_id,
            sdi.uom_id,
            sdi.accepted_quantity
        FROM supplier_delivery_item sdi
        WHERE sdi.supplier_delivery_id = p_supplier_delivery_id
          AND sdi.is_deleted = FALSE
        FOR UPDATE OF sdi
    LOOP
        v_item_count := v_item_count + 1;

        SELECT COALESCE(SUM(sdir.quantity), 0)
        INTO v_reference_sum
        FROM supplier_delivery_item_reference sdir
        WHERE sdir.supplier_delivery_item_id = v_item.supplier_delivery_item_id
          AND sdir.is_deleted = FALSE;

        IF v_reference_sum > 0 AND ABS(v_reference_sum - v_item.accepted_quantity) > 0.000001 THEN
            RAISE EXCEPTION
                'Accepted quantity % must equal reference total % for supplier delivery item %.',
                v_item.accepted_quantity,
                v_reference_sum,
                v_item.supplier_delivery_item_id;
        END IF;

        IF v_item.accepted_quantity > 0 THEN
            INSERT INTO stock_movement (
                source_id,
                destination_id,
                material_id,
                material_brand_id,
                quantity,
                uom_id,
                movement_type_id,
                status_id,
                movement_date,
                reference_code,
                notes,
                log_date_created,
                log_created_by_account_id,
                log_module_created
            ) VALUES (
                v_sd.supplier_id,
                v_sd.project_id,
                v_item.material_id,
                v_item.material_brand_id,
                v_item.accepted_quantity,
                v_item.uom_id,
                v_movement_type_receipt_id,
                v_movement_status_completed_id,
                COALESCE(v_sd.delivery_date, now()),
                v_sd.supplier_delivery_number,
                v_sd.notes,
                now(),
                COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                'supplier_delivery'
            ) RETURNING stock_movement_id INTO v_movement_id;

            UPDATE supplier_delivery_item
            SET stock_movement_id = v_movement_id,
                log_date_updated = now(),
                log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                log_module_updated = 'supplier_delivery'
            WHERE supplier_delivery_item_id = v_item.supplier_delivery_item_id;

            INSERT INTO stock_balance (
                party_id,
                material_id,
                material_brand_id,
                quantity_on_hand,
                uom_id,
                log_date_created,
                log_created_by_account_id,
                log_module_created
            )
            SELECT
                v_sd.project_id,
                v_item.material_id,
                v_item.material_brand_id,
                0,
                v_item.uom_id,
                now(),
                COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                'supplier_delivery'
            WHERE NOT EXISTS (
                SELECT 1
                FROM stock_balance sb
                WHERE sb.party_id = v_sd.project_id
                  AND sb.material_id = v_item.material_id
                  AND sb.uom_id = v_item.uom_id
                  AND (
                      (sb.material_brand_id IS NULL AND v_item.material_brand_id IS NULL)
                      OR sb.material_brand_id = v_item.material_brand_id
                  )
            );

            UPDATE stock_balance
            SET quantity_on_hand = quantity_on_hand + v_item.accepted_quantity,
                log_date_updated = now(),
                log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                log_module_updated = 'supplier_delivery'
            WHERE party_id = v_sd.project_id
              AND material_id = v_item.material_id
              AND uom_id = v_item.uom_id
              AND (
                  (material_brand_id IS NULL AND v_item.material_brand_id IS NULL)
                  OR material_brand_id = v_item.material_brand_id
              );

            INSERT INTO stock_layer (
                party_id,
                material_id,
                material_brand_id,
                uom_id,
                quantity_received,
                quantity_available,
                receive_date,
                source_movement_id,
                log_date_created,
                log_created_by_account_id,
                log_module_created
            ) VALUES (
                v_sd.project_id,
                v_item.material_id,
                v_item.material_brand_id,
                v_item.uom_id,
                v_item.accepted_quantity,
                v_item.accepted_quantity,
                COALESCE(v_sd.delivery_date, now()),
                v_movement_id,
                now(),
                COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                'supplier_delivery'
            );

            v_posted_item_count := v_posted_item_count + 1;
        END IF;

        FOR v_reference IN
            SELECT
                sdir.supplier_delivery_item_reference_id,
                sdir.reference_type_lookup_id,
                sdir.reference_id,
                sdir.reference_line_id,
                sdir.quantity,
                rt.code AS reference_type_code
            FROM supplier_delivery_item_reference sdir
            JOIN look_up rt ON rt.look_up_id = sdir.reference_type_lookup_id
            WHERE sdir.supplier_delivery_item_id = v_item.supplier_delivery_item_id
              AND sdir.is_deleted = FALSE
        LOOP
            IF v_reference.reference_type_code = 'po' THEN
                SELECT poi.ordered_quantity - poi.received_quantity
                INTO v_remaining_qty
                FROM purchase_order_item poi
                WHERE poi.purchase_order_item_id = v_reference.reference_line_id
                  AND poi.purchase_order_id = v_reference.reference_id
                  AND poi.is_deleted = FALSE
                FOR UPDATE;

                IF v_remaining_qty IS NULL THEN
                    RAISE EXCEPTION
                        'Purchase order line % does not belong to purchase order %.',
                        v_reference.reference_line_id,
                        v_reference.reference_id;
                END IF;

                IF v_reference.quantity > v_remaining_qty THEN
                    RAISE EXCEPTION
                        'Reference quantity % exceeds remaining PO quantity % for PO line %.',
                        v_reference.quantity,
                        v_remaining_qty,
                        v_reference.reference_line_id;
                END IF;

                UPDATE purchase_order_item
                SET received_quantity = received_quantity + v_reference.quantity,
                    log_date_updated = now(),
                    log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                    log_module_updated = 'supplier_delivery'
                WHERE purchase_order_item_id = v_reference.reference_line_id;

            ELSIF v_reference.reference_type_code = 'delivery_advice' THEN
                SELECT dai.advised_quantity - dai.received_quantity
                INTO v_remaining_qty
                FROM delivery_advice_item dai
                WHERE dai.delivery_advice_item_id = v_reference.reference_line_id
                  AND dai.delivery_advice_id = v_reference.reference_id
                  AND dai.is_deleted = FALSE
                FOR UPDATE;

                IF v_remaining_qty IS NULL THEN
                    RAISE EXCEPTION
                        'Delivery advice line % does not belong to delivery advice %.',
                        v_reference.reference_line_id,
                        v_reference.reference_id;
                END IF;

                IF v_reference.quantity > v_remaining_qty THEN
                    RAISE EXCEPTION
                        'Reference quantity % exceeds remaining delivery advice quantity % for line %.',
                        v_reference.quantity,
                        v_remaining_qty,
                        v_reference.reference_line_id;
                END IF;

                UPDATE delivery_advice_item
                SET received_quantity = received_quantity + v_reference.quantity,
                    log_date_updated = now(),
                    log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                    log_module_updated = 'supplier_delivery'
                WHERE delivery_advice_item_id = v_reference.reference_line_id;

            ELSIF v_reference.reference_type_code = 'material_request' THEN
                SELECT mri.requested_quantity
                INTO v_remaining_qty
                FROM material_request_item mri
                WHERE mri.material_request_item_id = v_reference.reference_line_id
                  AND mri.material_request_id = v_reference.reference_id
                  AND mri.is_deleted = FALSE
                FOR UPDATE;

                IF v_remaining_qty IS NULL THEN
                    RAISE EXCEPTION
                        'Material request line % does not belong to material request %.',
                        v_reference.reference_line_id,
                        v_reference.reference_id;
                END IF;

                SELECT COALESCE(SUM(r.quantity), 0)
                INTO v_posted_received_qty
                FROM supplier_delivery_item_reference r
                JOIN supplier_delivery_item i ON i.supplier_delivery_item_id = r.supplier_delivery_item_id AND i.is_deleted = FALSE
                JOIN supplier_delivery sd2 ON sd2.supplier_delivery_id = i.supplier_delivery_id AND sd2.is_deleted = FALSE
                JOIN look_up sds ON sds.look_up_id = sd2.status_id
                JOIN look_up rt2 ON rt2.look_up_id = r.reference_type_lookup_id
                WHERE r.is_deleted = FALSE
                  AND rt2.code = 'material_request'
                  AND r.reference_id = v_reference.reference_id
                  AND r.reference_line_id = v_reference.reference_line_id
                  AND (sds.code = 'posted' OR sd2.supplier_delivery_id = p_supplier_delivery_id);

                IF v_posted_received_qty > v_remaining_qty THEN
                    RAISE EXCEPTION
                        'Material request line % exceeds requested quantity: % > %.',
                        v_reference.reference_line_id,
                        v_posted_received_qty,
                        v_remaining_qty;
                END IF;
            END IF;
        END LOOP;
    END LOOP;

    IF v_item_count = 0 THEN
        RAISE EXCEPTION 'Supplier delivery % has no active line items to post.', p_supplier_delivery_id;
    END IF;

    IF v_posted_item_count = 0 THEN
        RAISE EXCEPTION 'Supplier delivery % has no accepted quantities to post.', p_supplier_delivery_id;
    END IF;

    FOR v_po_id IN
        SELECT sdpo.purchase_order_id
        FROM supplier_delivery_purchase_order sdpo
        WHERE sdpo.supplier_delivery_id = p_supplier_delivery_id
          AND sdpo.is_deleted = FALSE
    LOOP
        SELECT EXISTS (
            SELECT 1
            FROM purchase_order_item poi
            WHERE poi.purchase_order_id = v_po_id
              AND poi.is_deleted = FALSE
              AND poi.received_quantity < poi.ordered_quantity
        )
        INTO v_has_remaining;

        UPDATE purchase_order
        SET status_id = CASE WHEN v_has_remaining THEN v_po_status_partial_id ELSE v_po_status_delivered_id END,
            log_date_updated = now(),
            log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
            log_module_updated = 'supplier_delivery'
        WHERE purchase_order_id = v_po_id
          AND is_deleted = FALSE;
    END LOOP;

    IF v_da_status_completed_id IS NOT NULL THEN
        FOR v_da_id IN
            SELECT sdda.delivery_advice_id
            FROM supplier_delivery_delivery_advice sdda
            WHERE sdda.supplier_delivery_id = p_supplier_delivery_id
              AND sdda.is_deleted = FALSE
        LOOP
            SELECT EXISTS (
                SELECT 1
                FROM delivery_advice_item dai
                WHERE dai.delivery_advice_id = v_da_id
                  AND dai.is_deleted = FALSE
                  AND dai.received_quantity < dai.advised_quantity
            )
            INTO v_has_remaining;

            IF NOT v_has_remaining THEN
                UPDATE delivery_advice
                SET status_id = v_da_status_completed_id,
                    log_date_updated = now(),
                    log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                    log_module_updated = 'supplier_delivery'
                WHERE delivery_advice_id = v_da_id
                  AND is_deleted = FALSE;
            END IF;
        END LOOP;
    END IF;

    IF v_mr_status_completed_id IS NOT NULL THEN
        FOR v_mr_id IN
            SELECT sdmr.material_request_id
            FROM supplier_delivery_material_request sdmr
            WHERE sdmr.supplier_delivery_id = p_supplier_delivery_id
              AND sdmr.is_deleted = FALSE
        LOOP
            SELECT EXISTS (
                SELECT 1
                FROM material_request_item mri
                WHERE mri.material_request_id = v_mr_id
                  AND mri.is_deleted = FALSE
                  AND mri.requested_quantity > (
                    SELECT COALESCE(SUM(r.quantity), 0)
                    FROM supplier_delivery_item_reference r
                    JOIN supplier_delivery_item i ON i.supplier_delivery_item_id = r.supplier_delivery_item_id AND i.is_deleted = FALSE
                    JOIN supplier_delivery sd2 ON sd2.supplier_delivery_id = i.supplier_delivery_id AND sd2.is_deleted = FALSE
                    JOIN look_up sds ON sds.look_up_id = sd2.status_id
                    JOIN look_up rt2 ON rt2.look_up_id = r.reference_type_lookup_id
                    WHERE r.is_deleted = FALSE
                      AND rt2.code = 'material_request'
                      AND r.reference_id = v_mr_id
                      AND r.reference_line_id = mri.material_request_item_id
                      AND (sds.code = 'posted' OR sd2.supplier_delivery_id = p_supplier_delivery_id)
                  )
            )
            INTO v_has_remaining;

            IF NOT v_has_remaining THEN
                UPDATE material_request
                SET status_id = v_mr_status_completed_id,
                    log_date_updated = now(),
                    log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
                    log_module_updated = 'supplier_delivery'
                WHERE material_request_id = v_mr_id
                  AND is_deleted = FALSE;
            END IF;
        END LOOP;
    END IF;

    UPDATE supplier_delivery
    SET status_id = v_status_posted_id,
        posted_at = now(),
        posted_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
        log_date_updated = now(),
        log_updated_by_account_id = COALESCE(p_posted_by_account_id, v_sd.received_by_account_id),
        log_module_updated = 'supplier_delivery'
    WHERE supplier_delivery_id = p_supplier_delivery_id;

    RETURN p_supplier_delivery_id;
END;
$$;
